CREATE TABLE ledger_entries
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    version    INTEGER                     NOT NULL,
    entry_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    payee      VARCHAR                     NOT NULL,
    amount     NUMERIC                     NOT NULL,
    PRIMARY KEY (id)
);
