CREATE TABLE ledgers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL,
    name    VARCHAR NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO ledgers (id, version, name)
VALUES (1, 0, 'Default Ledger');

ALTER TABLE ledger_entries
    ADD COLUMN ledger_id INTEGER NOT NULL DEFAULT 1
        REFERENCES ledgers (id);

ALTER TABLE ledger_entries
    ALTER COLUMN ledger_id DROP DEFAULT;
