CREATE TABLE accounts
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL,
    name    VARCHAR NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO accounts (id, version, name)
SELECT id, 0, name
  FROM ledgers;

ALTER TABLE ledgers
    DROP COLUMN name,
    ADD COLUMN account_id INTEGER
        REFERENCES accounts (id);

UPDATE ledgers
   SET account_id = id;

ALTER TABLE ledgers
    ALTER COLUMN account_id SET NOT NULL;
