name: Release

on:
  push:
    branches:
      - release/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - id: pr-name
        name: Get pull request name
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: 'release/(.*)'
          string: ${{ github.ref_name }}
          replace-with: 'Release v$1'
      - name: Open pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: production
          pr_title: ${{ steps.pr-name.outputs.replaced }}
          pr_assignee: mddburgess
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: argent_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: zulu
          cache: maven
      - name: Build and test
        run: ./mvnw verify -B
        env:
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
      - name: Report
        uses: mddburgess/java-reporter-action@main
        if: ${{ always() }}
